/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.SerieVO;
import servicos.FilmeServicos;
import servicos.SerieServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Eloisa / Filipe Alves
 * @since 08/04/ 2017 - 12:53
 * @version 1.0
 */
public class GUICadSerie extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadSerie
     */
    public GUICadSerie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void cadastrar() {

        String MediaSelecionada = "";
        
        try {
            SerieVO sVO = new SerieVO();
            sVO.setNomeserie(jtNomeSerie.getText());
            sVO.setDiretorserie(jtDiretorSerie.getText());
            sVO.setAnoserie(Integer.parseInt(jtAnoSerie.getText()));
            sVO.setGeneroserie(jcbGeneroSerie.getSelectedItem().toString());
            sVO.setPositivoserie(jtaPontosPositivosSerie.getText());            
            sVO.setNegativoserie(jtaPontosNegativosSerie.getText());
            
            
            if(jrbBomSerie.isSelected()){
                MediaSelecionada = "Bom";
            }else if(jrbOtimoSerie.isSelected()){
                MediaSelecionada = "Bom";
            }else if(jrbRegularSerie.isSelected()){
                MediaSelecionada = "Regular";            
            }else if(jrbRuimSerie.isSelected()){
                MediaSelecionada = "Ruim";
            }
            
            sVO.setMediaserie(MediaSelecionada);           
            
            SerieServicos ss = ServicosFactory.getSerieServicos();
            ss.cadastrarSerie(sVO);
            
            JOptionPane.showMessageDialog(rootPane,
                    "Série Cadastrada com sucesso! ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro! " + e.getMessage(),
                    "Erro! ",
                    JOptionPane.ERROR_MESSAGE);

        }//fecha catch

    }//fecha cadastrar
    
    private void limpar(){
        jtNomeSerie.setText(null);
        jtDiretorSerie.setText(null);
        jtAnoSerie.setText(null);
        jcbGeneroSerie.setSelectedIndex(0);
        jtaPontosPositivosSerie.setText(null);
        jtaPontosNegativosSerie.setText(null);
        bgMediaSerie.clearSelection();
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMediaSerie = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNomeSerie = new javax.swing.JLabel();
        jtNomeSerie = new javax.swing.JTextField();
        jlDiretorSerie = new javax.swing.JLabel();
        jtDiretorSerie = new javax.swing.JTextField();
        jlAnoSerie = new javax.swing.JLabel();
        jtAnoSerie = new javax.swing.JTextField();
        jlGeneroSerie = new javax.swing.JLabel();
        jcbGeneroSerie = new javax.swing.JComboBox<>();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jlPontosPositivosSerie = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaPontosPositivosSerie = new javax.swing.JTextArea();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jlPontosNegativosSerie = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaPontosNegativosSerie = new javax.swing.JTextArea();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jlMediaSerie = new javax.swing.JLabel();
        jrbOtimoSerie = new javax.swing.JRadioButton();
        jrbBomSerie = new javax.swing.JRadioButton();
        jrbRegularSerie = new javax.swing.JRadioButton();
        jrbRuimSerie = new javax.swing.JRadioButton();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jbCadastrarSerie = new javax.swing.JButton();
        jbLimparSerie = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlNomeSerie.setText("Nome da série:");

        jlDiretorSerie.setText("Diretor:");

        jlAnoSerie.setText("Ano:");

        jlGeneroSerie.setText("Genero:");

        jcbGeneroSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terror", "Comédia", "Suspense", "Romance", "Drama", "Animação" }));
        jcbGeneroSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGeneroSerieActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jlNomeSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNomeSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlDiretorSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtDiretorSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlAnoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtAnoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlGeneroSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcbGeneroSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jlNomeSerie)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addComponent(jlDiretorSerie)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtDiretorSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jlAnoSerie)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtAnoSerie)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jlGeneroSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbGeneroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeSerie)
                    .addComponent(jtNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDiretorSerie)
                    .addComponent(jtDiretorSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAnoSerie)
                    .addComponent(jtAnoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGeneroSerie)
                    .addComponent(jcbGeneroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlPontosPositivosSerie.setText("Pontos positivos:");

        jtaPontosPositivosSerie.setColumns(20);
        jtaPontosPositivosSerie.setRows(5);
        jScrollPane1.setViewportView(jtaPontosPositivosSerie);

        jLayeredPane2.setLayer(jlPontosPositivosSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlPontosPositivosSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPontosPositivosSerie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlPontosNegativosSerie.setText("Pontos negativos:");

        jtaPontosNegativosSerie.setColumns(20);
        jtaPontosNegativosSerie.setRows(5);
        jScrollPane2.setViewportView(jtaPontosNegativosSerie);

        jLayeredPane3.setLayer(jlPontosNegativosSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlPontosNegativosSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPontosNegativosSerie)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlMediaSerie.setText("Média final:");

        bgMediaSerie.add(jrbOtimoSerie);
        jrbOtimoSerie.setText("Ótimo");

        bgMediaSerie.add(jrbBomSerie);
        jrbBomSerie.setText("Bom");

        bgMediaSerie.add(jrbRegularSerie);
        jrbRegularSerie.setText("Regular");

        bgMediaSerie.add(jrbRuimSerie);
        jrbRuimSerie.setText("Ruim");

        jLayeredPane4.setLayer(jlMediaSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrbOtimoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrbBomSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrbRegularSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jrbRuimSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMediaSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbOtimoSerie)
                .addGap(18, 18, 18)
                .addComponent(jrbBomSerie)
                .addGap(26, 26, 26)
                .addComponent(jrbRegularSerie)
                .addGap(18, 18, 18)
                .addComponent(jrbRuimSerie)
                .addGap(19, 19, 19))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMediaSerie)
                    .addComponent(jrbOtimoSerie)
                    .addComponent(jrbBomSerie)
                    .addComponent(jrbRegularSerie)
                    .addComponent(jrbRuimSerie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbCadastrarSerie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCadastrarSerie.setText("Cadastrar");
        jbCadastrarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarSerieActionPerformed(evt);
            }
        });
        jbCadastrarSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarSerieKeyPressed(evt);
            }
        });

        jbLimparSerie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbLimparSerie.setText("Limpar");
        jbLimparSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparSerieActionPerformed(evt);
            }
        });
        jbLimparSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbLimparSerieKeyPressed(evt);
            }
        });

        jLayeredPane5.setLayer(jbCadastrarSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jbLimparSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbCadastrarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimparSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimparSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane3)
                    .addComponent(jLayeredPane4)
                    .addComponent(jLayeredPane5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarSerieActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarSerieActionPerformed

    private void jbCadastrarSerieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarSerieKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            cadastrar();
            limpar();
        }
    }//GEN-LAST:event_jbCadastrarSerieKeyPressed

    private void jbLimparSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparSerieActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparSerieActionPerformed

    private void jbLimparSerieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLimparSerieKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            limpar();
        }
    }//GEN-LAST:event_jbLimparSerieKeyPressed

    private void jcbGeneroSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGeneroSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGeneroSerieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMediaSerie;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCadastrarSerie;
    private javax.swing.JButton jbLimparSerie;
    private javax.swing.JComboBox<String> jcbGeneroSerie;
    private javax.swing.JLabel jlAnoSerie;
    private javax.swing.JLabel jlDiretorSerie;
    private javax.swing.JLabel jlGeneroSerie;
    private javax.swing.JLabel jlMediaSerie;
    private javax.swing.JLabel jlNomeSerie;
    private javax.swing.JLabel jlPontosNegativosSerie;
    private javax.swing.JLabel jlPontosPositivosSerie;
    private javax.swing.JRadioButton jrbBomSerie;
    private javax.swing.JRadioButton jrbOtimoSerie;
    private javax.swing.JRadioButton jrbRegularSerie;
    private javax.swing.JRadioButton jrbRuimSerie;
    private javax.swing.JTextField jtAnoSerie;
    private javax.swing.JTextField jtDiretorSerie;
    private javax.swing.JTextField jtNomeSerie;
    private javax.swing.JTextArea jtaPontosNegativosSerie;
    private javax.swing.JTextArea jtaPontosPositivosSerie;
    // End of variables declaration//GEN-END:variables
}
