/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.SerieVO;
import servicos.SerieServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Eloisa / Filipe Alves
 * @since 08/04/ 2017 - 12:53
 * @version 1.0
 */
public class GUIManutencaoSerie extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIManutencaoSerie
     */
    
    DefaultTableModel dtms = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"idserie", "nomeserie","diretorserie",  "anoserie", "generoserie", "positivoserie", "negativoserie", "mediaserie"});
    
    
    
    
    public GUIManutencaoSerie() {
        initComponents();
        preencherTabelaSerie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSerie = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbPreencherSerie = new javax.swing.JButton();
        jbLimparSerie = new javax.swing.JButton();
        jbDeletarSerie = new javax.swing.JButton();
        jbAlterarSerie = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jtPesqSerie = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jlaIdSerie = new javax.swing.JLabel();
        jlaNomeSerie = new javax.swing.JLabel();
        jlaDiretorSerie = new javax.swing.JLabel();
        jlaAnoSerie = new javax.swing.JLabel();
        jlaGeneroSerie = new javax.swing.JLabel();
        jlaPositivoSerie = new javax.swing.JLabel();
        jlaNegativoSerie = new javax.swing.JLabel();
        jlaMediaSerie = new javax.swing.JLabel();
        jtaIdSerie = new javax.swing.JTextField();
        jtaNomeSerie = new javax.swing.JTextField();
        jtaDiretorSerie = new javax.swing.JTextField();
        jtaAnoSerie = new javax.swing.JTextField();
        jtaGeneroSerie = new javax.swing.JTextField();
        jtaPositivoSerie = new javax.swing.JTextField();
        jtaNegativoSerie = new javax.swing.JTextField();
        jtaMediaSerie = new javax.swing.JTextField();
        jbConfirmarAlteracaoSerie = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableSerie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSerie);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPreencherSerie.setText("Preencher");
        jbPreencherSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherSerieActionPerformed(evt);
            }
        });

        jbLimparSerie.setText("Limpar");
        jbLimparSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparSerieActionPerformed(evt);
            }
        });

        jbDeletarSerie.setText("Deletar");
        jbDeletarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarSerieActionPerformed(evt);
            }
        });

        jbAlterarSerie.setText("Alterar");
        jbAlterarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarSerieActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jbPreencherSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimparSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbDeletarSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbAlterarSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jbPreencherSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jbLimparSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jbDeletarSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAlterarSerie)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPreencherSerie)
                    .addComponent(jbLimparSerie)
                    .addComponent(jbDeletarSerie)
                    .addComponent(jbAlterarSerie))
                .addContainerGap())
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesqSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesqSerieActionPerformed(evt);
            }
        });
        jtPesqSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqSerieKeyReleased(evt);
            }
        });

        jLayeredPane3.setLayer(jtPesqSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtPesqSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jtPesqSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlaIdSerie.setText("ID");

        jlaNomeSerie.setText("Nome");

        jlaDiretorSerie.setText("Diretor");

        jlaAnoSerie.setText("Ano");

        jlaGeneroSerie.setText("Gênero");

        jlaPositivoSerie.setText("Positivos");

        jlaNegativoSerie.setText("Negativos");

        jlaMediaSerie.setText("Média");

        jbConfirmarAlteracaoSerie.setText("Confirmar Alteração");
        jbConfirmarAlteracaoSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoSerieActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(jlaIdSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaNomeSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaDiretorSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaAnoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaGeneroSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaPositivoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaNegativoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaMediaSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaIdSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaNomeSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaDiretorSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaAnoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaGeneroSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaPositivoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaNegativoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaMediaSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jbConfirmarAlteracaoSerie, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaGeneroSerie)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaIdSerie)
                            .addComponent(jlaNomeSerie)
                            .addComponent(jlaDiretorSerie)
                            .addComponent(jlaAnoSerie)
                            .addComponent(jlaPositivoSerie)
                            .addComponent(jlaNegativoSerie)
                            .addComponent(jlaMediaSerie))
                        .addGap(49, 49, 49)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtaMediaSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jtaGeneroSerie)
                            .addComponent(jtaIdSerie)
                            .addComponent(jtaNomeSerie)
                            .addComponent(jtaDiretorSerie)
                            .addComponent(jtaAnoSerie)
                            .addComponent(jtaPositivoSerie)
                            .addComponent(jtaNegativoSerie))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmarAlteracaoSerie)
                .addGap(53, 53, 53))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaIdSerie)
                            .addComponent(jtaIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaNomeSerie)
                            .addComponent(jtaNomeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaDiretorSerie)
                            .addComponent(jtaDiretorSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaAnoSerie)
                            .addComponent(jtaAnoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlaGeneroSerie)
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtaGeneroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbConfirmarAlteracaoSerie)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtaPositivoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlaPositivoSerie))
                        .addGap(18, 18, 18)
                        .addComponent(jlaNegativoSerie))
                    .addComponent(jtaNegativoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlaMediaSerie)
                    .addComponent(jtaMediaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLayeredPane1)
                                    .addComponent(jLayeredPane2))))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPreencherSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherSerieActionPerformed
        limparTabelaSerie();
        preencherTabelaSerie();
    }//GEN-LAST:event_jbPreencherSerieActionPerformed

    private void jbLimparSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparSerieActionPerformed
        limparTabelaSerie();
    }//GEN-LAST:event_jbLimparSerieActionPerformed

    private void jtPesqSerieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqSerieKeyReleased
        limparTabelaSerie();
        filtrarSerie();
    }//GEN-LAST:event_jtPesqSerieKeyReleased

    private void jbDeletarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarSerieActionPerformed
        deletarSerie();
        limparTabelaSerie();
        preencherTabelaSerie();
    }//GEN-LAST:event_jbDeletarSerieActionPerformed

    private void jbAlterarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarSerieActionPerformed
        alterarSerie();
        limparTabelaSerie();
        preencherTabelaSerie();
    }//GEN-LAST:event_jbAlterarSerieActionPerformed

    private void jbConfirmarAlteracaoSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoSerieActionPerformed
        confirmarAlteracaoSerie();
        limparTabelaSerie();
        preencherTabelaSerie();
    }//GEN-LAST:event_jbConfirmarAlteracaoSerieActionPerformed

    private void jtPesqSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesqSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesqSerieActionPerformed

    private void preencherTabelaSerie(){
        
        try {
            
            SerieServicos ss = ServicosFactory.getSerieServicos();
            
            ArrayList<SerieVO> series = new ArrayList<>();
            
            series = ss.buscarSerie();
            for (int i = 0; i < series.size(); i++){
                dtms.addRow(new String[]{
                String.valueOf(series.get(i).getIdSerie()),
                String.valueOf(series.get(i).getNomeserie()),
                String.valueOf(series.get(i).getDiretorserie()),
                String.valueOf(series.get(i).getAnoserie()),
                String.valueOf(series.get(i).getGeneroserie()),
                String.valueOf(series.get(i).getPositivoserie()),
                String.valueOf(series.get(i).getNegativoserie()),
                String.valueOf(series.get(i).getMediaserie())});
                
            }//fecha for
            
            jTableSerie.setModel(dtms);
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO! "+e.getMessage());
        }//fecha catch
        
    }//fecha preencher tabela serie
    private void limparTabelaSerie(){
        dtms.setNumRows(0);
    }//fecha limpar tabela
    
    private void deletarSerie() {
        try {
            /* Buscando a linha que o usuário clicou */
            int linha = jTableSerie.getSelectedRow();
            
            /* Testando se o usuário selecionou alguma linha. */
            if (linha == -1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Você não selecionou nenhuma linha!");
            } else {
                SerieServicos ss = ServicosFactory.getSerieServicos();
                
                /* Buscando o idProduto da linha selecionada. O zero(0) indica
                   que vamos buscar o valor da primeira coluna. */
                String idSerie = (String) jTableSerie.getValueAt(linha, 0);
                
                /* Enviando o idProduto para ser excluido. */
                ss.deletarSerie(Long.parseLong(idSerie));

                //Mensagem de sucesso para o usuário!
                JOptionPane.showMessageDialog(this,
                        "Serie excluida com sucesso!");

            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao deletar! " + e.getMessage());
        }//fecha catch        
    }//fecha deletar
    
    private void filtrarSerie(){
        
        try {
            if (jtPesqSerie.getText() .toString().isEmpty()) {
                limparTabelaSerie();
                preencherTabelaSerie();
            }else{
                String query = "";
                //String filtro = jComboFiltroSerie.getSelectedItem().toString();
                
                /*if (filtro.equalsIgnoreCase("nomefilme")){
                    query = "where nomeserie like '%"+jtPesqSerie.getText()+"%'";
                }else if (filtro.equalsIgnoreCase("diretorserie")){
                    query = "where diretoserie="+jtPesqSerie.getText();
                }else if (filtro.equalsIgnoreCase("anoserie")){
                    query = "where anoserie="+jtPesqSerie.getText();
                }else if (filtro.equalsIgnoreCase("generoserie")){
                    query = "where generoserie="+jtPesqSerie.getText();
                }else if (filtro.equalsIgnoreCase("positivoserie")){
                    query = "where positivoserie="+jtPesqSerie.getText();
                }else if (filtro.equalsIgnoreCase("negativoserie")){
                    query = "where negativoserie="+jtPesqSerie.getText();
                }else if (filtro.equalsIgnoreCase("mediaserie")){
                    query = "where mediaserie="+jtPesqSerie.getText();
                }*///fecha else if
                
                
                query = "WHERE serie.`idSerie`        LIKE '%" + jtPesqSerie.getText() + "%'"  
                        +"    OR serie.nomeserie      LIKE '%" + jtPesqSerie.getText() + "%'"
                        +"    OR serie.diretorserie   LIKE '%" + jtPesqSerie.getText() + "%'"
                        +"    OR serie.anoserie       LIKE '%" + jtPesqSerie.getText() + "%'"
                        +"    OR serie.generoserie    LIKE '%" + jtPesqSerie.getText() + "%'"
                        +"    OR serie.positivoserie  LIKE '%" + jtPesqSerie.getText() + "%'"
                        +"    OR serie.negativoserie  LIKE '%" + jtPesqSerie.getText() + "%'"
                        +"    OR serie.mediaserie     LIKE '%" + jtPesqSerie.getText() + "%'";
                        
                        
                        
                        
                        
                        
                
                SerieServicos ss = ServicosFactory.getSerieServicos();
                
                ArrayList<SerieVO> series = new ArrayList<>();
                series = ss.filtrar(query);
                
               for (int i = 0; i < series.size(); i++) {
                dtms.addRow(new String[]{
                String.valueOf(series.get(i).getIdSerie()),
                String.valueOf(series.get(i).getNomeserie()),
                String.valueOf(series.get(i).getDiretorserie()),
                String.valueOf(series.get(i).getAnoserie()),
                String.valueOf(series.get(i).getGeneroserie()),
                String.valueOf(series.get(i).getPositivoserie()),
                String.valueOf(series.get(i).getMediaserie())});
            
        }//fecha for
               
               jTableSerie.setModel(dtms);
         
            }//fecha classe
                
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "ERRO! " + e.getMessage());
        }//fecha catch
        
    }//fecha filtrar
    
        private void alterarSerie(){
        int linha = jTableSerie.getSelectedRow();
        if(linha != -1){
            jtaIdSerie.setText((String) jTableSerie.getValueAt(linha, 0));
            jtaNomeSerie.setText((String) jTableSerie.getValueAt(linha, 1));
            jtaDiretorSerie.setText((String) jTableSerie.getValueAt(linha, 2));
            jtaAnoSerie.setText((String) jTableSerie.getValueAt(linha, 3));
            jtaGeneroSerie.setText((String) jTableSerie.getValueAt(linha, 4));
            jtaPositivoSerie.setText((String) jTableSerie.getValueAt(linha, 5));
            jtaNegativoSerie.setText((String) jTableSerie.getValueAt(linha, 6));
            jtaMediaSerie.setText((String) jTableSerie.getValueAt(linha, 7));
        }else{
            JOptionPane.showMessageDialog(this, "Você não selecionou nenhuma linha! ");
            
        }//fecha else
    
    }//fecha método
    
    private void confirmarAlteracaoSerie(){
        try {
            SerieVO svo = new SerieVO();
            svo.setIdSerie(Long.parseLong(jtaIdSerie.getText()));
            svo.setNomeserie(jtaNomeSerie.getText());
            svo.setDiretorserie(jtaDiretorSerie.getText());
            svo.setAnoserie(Integer.parseInt(jtaAnoSerie.getText()));
            svo.setGeneroserie(jtaGeneroSerie.getText());
            svo.setPositivoserie(jtaPositivoSerie.getText());
            svo.setNegativoserie(jtaNegativoSerie.getText());
            svo.setMediaserie(jtaMediaSerie.getText());
            
            SerieServicos ss = ServicosFactory.getSerieServicos();
            ss.alterarSerie(svo);
            
            JOptionPane.showMessageDialog(this, "Alterado com sucesso! ");
            limparTabelaSerie();
            preencherTabelaSerie();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO! "+e.getMessage());
        }//fecha catch
    }//fecha metodo
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSerie;
    private javax.swing.JButton jbAlterarSerie;
    private javax.swing.JButton jbConfirmarAlteracaoSerie;
    private javax.swing.JButton jbDeletarSerie;
    private javax.swing.JButton jbLimparSerie;
    private javax.swing.JButton jbPreencherSerie;
    private javax.swing.JLabel jlaAnoSerie;
    private javax.swing.JLabel jlaDiretorSerie;
    private javax.swing.JLabel jlaGeneroSerie;
    private javax.swing.JLabel jlaIdSerie;
    private javax.swing.JLabel jlaMediaSerie;
    private javax.swing.JLabel jlaNegativoSerie;
    private javax.swing.JLabel jlaNomeSerie;
    private javax.swing.JLabel jlaPositivoSerie;
    private javax.swing.JTextField jtPesqSerie;
    private javax.swing.JTextField jtaAnoSerie;
    private javax.swing.JTextField jtaDiretorSerie;
    private javax.swing.JTextField jtaGeneroSerie;
    private javax.swing.JTextField jtaIdSerie;
    private javax.swing.JTextField jtaMediaSerie;
    private javax.swing.JTextField jtaNegativoSerie;
    private javax.swing.JTextField jtaNomeSerie;
    private javax.swing.JTextField jtaPositivoSerie;
    // End of variables declaration//GEN-END:variables
}
