/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.FilmeVO;
import servicos.FilmeServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Eloisa / Filipe Alves
 * @since 08/04/ 2017 - 12:53
 * @version 1.0
 */
public class GUIManutencao extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIManutencao
     */
    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"idfilme", "nomefilme", "diretorfilme", "anofilme", "generofilme", "positivofilme", "negativofilme", "mediafilme"});

    public GUIManutencao() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilme = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbPreencher = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletarFilme = new javax.swing.JButton();
        jbAlterarFilme = new javax.swing.JButton();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jtPesqFilme = new javax.swing.JTextField();
        jComboFiltroFilme = new javax.swing.JComboBox<>();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jlaNomeFilme = new javax.swing.JLabel();
        jlaDiretorFilme = new javax.swing.JLabel();
        jlaAnoFilme = new javax.swing.JLabel();
        jlaGeneroFilme = new javax.swing.JLabel();
        jlaPositivosFilme = new javax.swing.JLabel();
        jlaNegativoFilme = new javax.swing.JLabel();
        jlaMediaFilme = new javax.swing.JLabel();
        jtaNomeFilme = new javax.swing.JTextField();
        jtaDiretorFilme = new javax.swing.JTextField();
        jtaAnoFilme = new javax.swing.JTextField();
        jtaGeneroFilme = new javax.swing.JTextField();
        jtaPositivosFilme = new javax.swing.JTextField();
        jtaNegativoFilme = new javax.swing.JTextField();
        jtaMediaFilme = new javax.swing.JTextField();
        jlaIdFilme = new javax.swing.JLabel();
        jtaIdFilme = new javax.swing.JTextField();
        jbConfirmarAlteracaoFilme = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableFilme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome do Filme", "Diretor do Filme", "Ano do Filme", "Genero do Filme", "Pontos Positivos]", "Pontos Negativos", "Media do Fime"
            }
        ));
        jScrollPane1.setViewportView(jTableFilme);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPreencher.setText("Preencher");
        jbPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbDeletarFilme.setText("Deletar");
        jbDeletarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarFilmeActionPerformed(evt);
            }
        });

        jbAlterarFilme.setText("Alterar");
        jbAlterarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarFilmeActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jbPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbDeletarFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbAlterarFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jbPreencher)
                .addGap(87, 87, 87)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jbDeletarFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jbAlterarFilme)
                .addGap(35, 35, 35))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPreencher)
                    .addComponent(jbLimpar)
                    .addComponent(jbDeletarFilme)
                    .addComponent(jbAlterarFilme))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesqFilme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqFilmeKeyReleased(evt);
            }
        });

        jComboFiltroFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboFiltroFilme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboFiltroFilmeItemStateChanged(evt);
            }
        });

        jLayeredPane3.setLayer(jtPesqFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jComboFiltroFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtPesqFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jComboFiltroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesqFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboFiltroFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlaNomeFilme.setText("Nome");

        jlaDiretorFilme.setText("Diretor");

        jlaAnoFilme.setText("Ano");

        jlaGeneroFilme.setText("Genero");

        jlaPositivosFilme.setText("Positivos");

        jlaNegativoFilme.setText("Negativos");

        jlaMediaFilme.setText("Média Final");

        jlaIdFilme.setText("ID");

        jLayeredPane4.setLayer(jlaNomeFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaDiretorFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaAnoFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaGeneroFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaPositivosFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaNegativoFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaMediaFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaNomeFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaDiretorFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaAnoFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaGeneroFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaPositivosFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaNegativoFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaMediaFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlaIdFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtaIdFilme, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jlaIdFilme)
                        .addGap(18, 18, 18)
                        .addComponent(jtaIdFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlaDiretorFilme)
                                    .addComponent(jlaNomeFilme))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtaNomeFilme, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(jtaDiretorFilme)))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlaAnoFilme)
                                    .addComponent(jlaGeneroFilme))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtaGeneroFilme, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(jtaAnoFilme)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane4Layout.createSequentialGroup()
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlaPositivosFilme)
                                    .addComponent(jlaNegativoFilme)
                                    .addComponent(jlaMediaFilme))
                                .addGap(9, 9, 9)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtaMediaFilme)
                                    .addComponent(jtaPositivosFilme)
                                    .addComponent(jtaNegativoFilme))))
                        .addGap(37, 37, 37))))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlaIdFilme)
                    .addComponent(jtaIdFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaNomeFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtaNomeFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaDiretorFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtaDiretorFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtaAnoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlaAnoFilme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlaGeneroFilme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtaGeneroFilme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtaPositivosFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlaPositivosFilme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtaNegativoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlaNegativoFilme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlaMediaFilme)
                    .addComponent(jtaMediaFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jbConfirmarAlteracaoFilme.setText("Confirmar alteração");
        jbConfirmarAlteracaoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoFilmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jbConfirmarAlteracaoFilme))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jbConfirmarAlteracaoFilme)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbPreencherActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();// TODO add your handling code here:
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtPesqFilmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqFilmeKeyReleased
        limparTabela();
        filtarFilme();
    }//GEN-LAST:event_jtPesqFilmeKeyReleased

    private void jbDeletarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarFilmeActionPerformed
        deletar();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbDeletarFilmeActionPerformed

    private void jComboFiltroFilmeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboFiltroFilmeItemStateChanged
        limparTabela();
        filtarFilme();
    }//GEN-LAST:event_jComboFiltroFilmeItemStateChanged

    private void jbConfirmarAlteracaoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoFilmeActionPerformed
        confirmarAlteracaoFilme();
    }//GEN-LAST:event_jbConfirmarAlteracaoFilmeActionPerformed

    private void jbAlterarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarFilmeActionPerformed
        alterarFilme();
    }//GEN-LAST:event_jbAlterarFilmeActionPerformed

    private void preencherTabela() {
        
        try{
        
        FilmeServicos fs = ServicosFactory.getFilmeServicos();

        ArrayList<FilmeVO> films = new ArrayList<>();

        films = fs.buscarFilme();

        for (int i = 0; i < films.size(); i++) {
            dtm.addRow(new String[]{
                String.valueOf(films.get(i).getIdFilme()),
                String.valueOf(films.get(i).getNomefilme()),
                String.valueOf(films.get(i).getDiretorfilme()),
                String.valueOf(films.get(i).getAnofilme()),
                String.valueOf(films.get(i).getGenerofilme()),
                String.valueOf(films.get(i).getPositivofilme()),
                String.valueOf(films.get(i).getMediafilme()),});
            
        }//fecha for
        
        jTableFilme.setModel(dtm);

    
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO! "+e.getMessage());
            
        }//fecha catch    
    }//fecha preencher 
    
    private void limparTabela(){
        dtm.setNumRows(0);
    }//fecha limpar tabela
    
    private void deletar() {
        try {
            /* Buscando a linha que o usuário clicou */
            int linha = jTableFilme.getSelectedRow();
            
            /* Testando se o usuário selecionou alguma linha. */
            if (linha == -1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Você não selecionou nenhuma linha!");
            } else {
                FilmeServicos fs = ServicosFactory.getFilmeServicos();
                
                /* Buscando o idProduto da linha selecionada. O zero(0) indica
                   que vamos buscar o valor da primeira coluna. */
                String idFilme = (String) jTableFilme.getValueAt(linha, 0);
                
                /* Enviando o idProduto para ser excluido. */
                fs.deletarFilme(Long.parseLong(idFilme));

                //Mensagem de sucesso para o usuário!
                JOptionPane.showMessageDialog(this,
                        "Filme excluido com sucesso!");

            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Erro ao deletar! " + e.getMessage());
        }//fecha catch        
    }//fecha deletar
    
    private void filtarFilme(){
        
        try {
            if (jtPesqFilme.getText() .toString().isEmpty()) {
                limparTabela();
                preencherTabela();
            }else{
                String query = "";
                String filtro = jComboFiltroFilme.getSelectedItem().toString();
                
                if (filtro.equalsIgnoreCase("nomefilme")){
                    query = "where nomefilme like '%"+jtPesqFilme.getText()+"%'";
                }else if (filtro.equalsIgnoreCase("diretorfilme")){
                    query = "where diretofilme="+jtPesqFilme.getText();
                }else if (filtro.equalsIgnoreCase("anofilme")){
                    query = "where anofilme="+jtPesqFilme.getText();
                }else if (filtro.equalsIgnoreCase("generofilme")){
                    query = "where generofilme="+jtPesqFilme.getText();
                }else if (filtro.equalsIgnoreCase("positivofilme")){
                    query = "where positivofilme="+jtPesqFilme.getText();
                }else if (filtro.equalsIgnoreCase("negativofilme")){
                    query = "where negativofilme="+jtPesqFilme.getText();
                }else if (filtro.equalsIgnoreCase("mediafilme")){
                    query = "where mediafilme="+jtPesqFilme.getText();
                }//fecha else if
                
                FilmeServicos fs = ServicosFactory.getFilmeServicos();
                
                ArrayList<FilmeVO> films = new ArrayList<>();
                films = fs.filtrar(query);
                
               for (int i = 0; i < films.size(); i++) {
                dtm.addRow(new String[]{
                String.valueOf(films.get(i).getIdFilme()),
                String.valueOf(films.get(i).getNomefilme()),
                String.valueOf(films.get(i).getDiretorfilme()),
                String.valueOf(films.get(i).getAnofilme()),
                String.valueOf(films.get(i).getGenerofilme()),
                String.valueOf(films.get(i).getPositivofilme()),
                String.valueOf(films.get(i).getMediafilme()),});
            
        }//fecha for
               
               jTableFilme.setModel(dtm);
         
            }//fecha classe
                
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "ERRO! " + e.getMessage());
        }//fecha catch
        
    }//fecha filtrar

    
    private void alterarFilme(){
        int linha = jTableFilme.getSelectedRow();
        if(linha != -1){
            jtaIdFilme.setText((String) jTableFilme.getValueAt(linha, 0));
            jtaNomeFilme.setText((String) jTableFilme.getValueAt(linha, 1));
            jtaDiretorFilme.setText((String) jTableFilme.getValueAt(linha, 2));
            jtaAnoFilme.setText((String) jTableFilme.getValueAt(linha, 3));
            jtaGeneroFilme.setText((String) jTableFilme.getValueAt(linha, 4));
            jtaPositivosFilme.setText((String) jTableFilme.getValueAt(linha, 5));
            jtaNegativoFilme.setText((String) jTableFilme.getValueAt(linha, 6));
            jtaMediaFilme.setText((String) jTableFilme.getValueAt(linha, 7));
        }else{
            JOptionPane.showMessageDialog(this, "Você não selecionou nenhuma linha! ");
            
        }//fecha else
    
    }//fecha método
    
    private void confirmarAlteracaoFilme(){
        try {
            FilmeVO fvo = new FilmeVO();
            fvo.setIdFilme(Long.parseLong(jtaIdFilme.getText()));
            fvo.setNomefilme(jtaNomeFilme.getText());
            fvo.setDiretorfilme(jtaDiretorFilme.getText());
            fvo.setAnofilme(Integer.parseInt(jtaAnoFilme.getText()));
            fvo.setGenerofilme(jtaGeneroFilme.getText());
            fvo.setPositivofilme(jtaPositivosFilme.getText());
            fvo.setNegativofilme(jtaNegativoFilme.getText());
            fvo.setMediafilme(jtaMediaFilme.getText());
            
            FilmeServicos fs = ServicosFactory.getFilmeServicos();
            fs.alterarFilme(fvo);
            
            JOptionPane.showMessageDialog(this, "Alterado com sucesso! ");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO! "+e.getMessage());
        }//fecha catch
    }//fecha metodo
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboFiltroFilme;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFilme;
    private javax.swing.JButton jbAlterarFilme;
    private javax.swing.JButton jbConfirmarAlteracaoFilme;
    private javax.swing.JButton jbDeletarFilme;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPreencher;
    private javax.swing.JLabel jlaAnoFilme;
    private javax.swing.JLabel jlaDiretorFilme;
    private javax.swing.JLabel jlaGeneroFilme;
    private javax.swing.JLabel jlaIdFilme;
    private javax.swing.JLabel jlaMediaFilme;
    private javax.swing.JLabel jlaNegativoFilme;
    private javax.swing.JLabel jlaNomeFilme;
    private javax.swing.JLabel jlaPositivosFilme;
    private javax.swing.JTextField jtPesqFilme;
    private javax.swing.JTextField jtaAnoFilme;
    private javax.swing.JTextField jtaDiretorFilme;
    private javax.swing.JTextField jtaGeneroFilme;
    private javax.swing.JTextField jtaIdFilme;
    private javax.swing.JTextField jtaMediaFilme;
    private javax.swing.JTextField jtaNegativoFilme;
    private javax.swing.JTextField jtaNomeFilme;
    private javax.swing.JTextField jtaPositivosFilme;
    // End of variables declaration//GEN-END:variables
}
